media:
  input: public/images/uploads
  output: /images/uploads

# Pages CMS uses `content:` (not `collections:`) and `type` (not `widget`)
content:
  # ─────────────────────────────────────────────
  # Practice-wide site settings (JSON singleton)
  # ─────────────────────────────────────────────
  - name: siteSettings
    label: Site settings
    type: file
    path: src/content/siteSettings/practice.json
    format: json
    fields:
      - name: practiceName
        label: Practice name
        type: string
      - name: tagline
        label: Tagline
        type: string
      - name: city
        label: City
        type: string
      - name: state
        label: State / Region
        type: string
      - name: phone
        label: Phone
        type: string
      - name: email
        label: Email
        type: string
        required: false
      - name: addressLine1
        label: Address line 1
        type: string
      - name: addressLine2
        label: Address line 2
        type: string
        required: false
      - name: googleMapsUrl
        label: Google Maps URL
        type: string
        required: false
      - name: hours
        label: Hours
        type: object
        list: true
        required: false
        fields:
          - name: label
            label: Label
            type: string
          - name: value
            label: Value
            type: string
      - name: nav
        label: Navigation
        type: object
        list: true
        required: false
        fields:
          - name: label
            label: Label
            type: string
          - name: href
            label: Href
            type: string
      - name: socials
        label: Social links
        type: object
        list: true
        required: false
        fields:
          - name: label
            label: Label
            type: string
          - name: href
            label: Href
            type: string

  # ─────────────────────────────────────────────
  # Home page singleton (hero + high-level copy)
  # ─────────────────────────────────────────────
  - name: home
    label: Home
    type: file
    path: src/content/home/home.md
    # default markdown + YAML frontmatter
    format: yaml-frontmatter
    bodyField: body
    fields:
      - name: title
        label: Title
        type: string
        hidden: true
        default: home
      - name: heroHeadline
        label: Hero headline
        type: string
      - name: heroSubheadline
        label: Hero subheadline
        type: text
      - name: heroBadge
        label: Hero badge
        type: string
        required: false
      - name: heroPrimaryCtaLabel
        label: Primary CTA label
        type: string
      - name: heroPrimaryCtaHref
        label: Primary CTA href
        type: string
      - name: heroSecondaryCtaLabel
        label: Secondary CTA label
        type: string
      - name: heroSecondaryCtaHref
        label: Secondary CTA href
        type: string
      - name: reviewLine
        label: Review strip line
        type: string
        required: false
      - name: insuranceNote
        label: Insurance note
        type: string
        required: false

  # ─────────────────────────────────────────────
  # Generic pages (About, New Patients, etc.)
  # ─────────────────────────────────────────────
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    format: yaml-frontmatter
    bodyField: body
    view:
      labelField: title
      fields: [title, slug]
      sort: title
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: layout
        label: Layout
        type: string
        options:
          - default
          - narrow
        default: default
      - name: intro
        label: Intro
        type: text
        required: false

  # ─────────────────────────────────────────────
  # Team / doctors
  # ─────────────────────────────────────────────
  - name: team
    label: Team
    type: collection
    path: src/content/team
    format: yaml-frontmatter
    bodyField: body
    view:
      labelField: name
      fields: [name, role]
      sort: order
    fields:
      - name: name
        label: Name
        type: string
      - name: slug
        label: Slug
        type: string
      - name: role
        label: Role
        type: string
      - name: credentials
        label: Credentials
        type: string
        list: true
        required: false
      - name: badges
        label: Badges
        type: string
        list: true
        required: false
      - name: headshot
        label: Headshot (image path or URL)
        type: string
        required: false
      - name: bioShort
        label: Short bio
        type: text
      - name: bioLong
        label: Long bio
        type: text
        required: false
      - name: focusAreas
        label: Focus areas
        type: string
        list: true
        required: false
      - name: order
        label: Order
        type: number
        default: 0

  # ─────────────────────────────────────────────
  # Services / treatments
  # ─────────────────────────────────────────────
  - name: services
    label: Services
    type: collection
    path: src/content/services
    format: yaml-frontmatter
    bodyField: body
    view:
      labelField: name
      fields: [name, category]
      sort: order
    fields:
      - name: name
        label: Name
        type: string
      - name: slug
        label: Slug
        type: string
      - name: category
        label: Category
        type: string
        required: false
      - name: tagline
        label: Tagline
        type: string
        required: false
      - name: summary
        label: Summary
        type: text
      - name: order
        label: Order
        type: number
        default: 0
      - name: featured
        label: Featured
        type: boolean
        default: false

  # ─────────────────────────────────────────────
  # Blog posts
  # ─────────────────────────────────────────────
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    format: yaml-frontmatter
    bodyField: body
    view:
      labelField: title
      fields: [title, date]
      sort: date
      sortDirection: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: date
        label: Date
        type: datetime
      - name: excerpt
        label: Excerpt
        type: text
      - name: tags
        label: Tags
        type: string
        list: true
        required: false
